### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by danhab05** [Androz2091/node-ecole-directe#1]
Bonjour j'aimerais savoir comment utiliser ce depot
j'ai clone le depot avec 
`git clone https://github.com/Androz2091/node-ecole-directe`
je me suis ensuite deplace dans le dossier
`cd node-ecole-directe `
puis j'ai effectué
`npm install`
jusque ici tout va bien mais au moment de la commande 
`npm start`
j'ai une erreur :
`npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/username/.npm/_logs/2020-07-17T17_54_17_545Z-debug.log`

et voici le 
`cat /home/username/.npm/_logs/2020-07-17T17_54_17_545Z-debug.log`

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/share/npm/lib/run-script.js:155:19)
4 verbose stack     at /usr/share/npm/lib/run-script.js:63:5
4 verbose stack     at /usr/share/nodejs/read-package-json/read-json.js:116:5
4 verbose stack     at /usr/share/nodejs/read-package-json/read-json.js:436:5
4 verbose stack     at checkBinReferences_ (/usr/share/nodejs/read-package-json/read-json.js:391:45)
4 verbose stack     at final (/usr/share/nodejs/read-package-json/read-json.js:434:3)
4 verbose stack     at then (/usr/share/nodejs/read-package-json/read-json.js:161:5)
4 verbose stack     at /usr/share/nodejs/read-package-json/read-json.js:382:12
4 verbose stack     at /usr/share/nodejs/graceful-fs/graceful-fs.js:115:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
5 verbose cwd /home/snowy/node-ecole-directe
6 verbose Linux 5.4.0-40-generic
7 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
8 verbose node v10.19.0
9 verbose npm  v6.14.4
10 error missing script: start
11 verbose exit [ 1, true ]`

Merci de votre aide

**Comment by phileas0408** [comment]
bonjour, j'ai la même erreur, pas de solution?

**Comment by Androz2091** [comment]
`npm start` ne fonctionne pas pour les librairies. Suivez le readme.
