### ISSUE TITLE
Devoirs

### ISSUE THREAD

**Issue by TiotBenjy** [Androz2091/node-ecole-directe#2]
bonjour , @Androz2091 j'aimerais savoir si il est possible de récupérer le contenu du devoir par ex ("faire exercice x p x"), en plus de la matière etc ?

**Comment by Androz2091** [comment]
Bonjour, c'est peut-être possible mais à vrai dire je n'ai pas d'identifiants pour faire mes tests...

**Comment by TiotBenjy** [comment]
ok pas de problème

**Comment by Androz2091** [comment]
Si vous avez des identifiants que vous souhaitez partager pour que je mette à jour la librairie, vous pouvez me contacter via Discord (Androz#2091). Je ferme cette issue car je ne pourrai pas la mettre à jour sans identifiants.
