### ISSUE TITLE
Moyenne Générale

### ISSUE THREAD

**Issue by Zaphkiel-Ivanovna** [Androz2091/node-ecole-directe#3]
Bonjour,
Je voudrais savoir si il est possible d'avoir la moyenne de chaque matière et générale depuis L'API. 

Merci d'avance

**Comment by Androz2091** [comment]
Bonjour, oui bien sur :
```js
const EcoleDirecte = require("node-ecole-directe");
const session = new EcoleDirecte.Session();
(async () => {
    const account = await session.connexion("nom", "mot-de-passe");

    account.fetchNotes().then((notes) => {
        const trimestre = notes.periodes.find((periode) => periode.periode === '1er trimestre 2020-2021');
        
        // Récupérer les moyennes générales
        const moyenneGeneraleEleve = trimestre.ensembleMatieres.moyenneGenerale;
        const moyenneGeneraleClasse = trimestre.ensembleMatieres.moyenneClasse;

        // Récupérer les moyennes de maths
        const moyenneMathsEleve = trimestre.ensembleMatieres.disciplines.find((discipline) => discipline.codeMatiere === 'MATHS').moyenne;
        const moyenneMathsClasse = trimestre.ensembleMatieres.disciplines.find((discipline) => discipline.codeMatiere === 'MATHS').moyenneClasse;

        console.log(moyenneGeneraleEleve, moyenneGeneraleClasse, moyenneMathsEleve, moyenneMathsClasse);
    })
})()

```

**Comment by Zaphkiel-Ivanovna** [comment]
Merci beaucoup du code.

Avez vous une doc complète sur l'API Ecole Directe ?

**Comment by Derpinou** [comment]
Bonjour, il me semble qu'il n'y a pas d'api publique, mais j'ai trouver cette documentation :
https://documenter.getpostman.com/view/11643143/SztK1QKb#7475ebe9-b31b-4853-ad46-87612425b168

**Comment by Androz2091** [comment]
Non pas du tout, honnêtement je n'ai pas le temps de me lancer dans la rédaction d'une doc pour ce projet. Je suis toujours là pour répondre s'il y a des questions (et sinon tu peux simplement utiliser console.log pour voir ce que renvoies telle ou telle méthode)

**Comment by Zaphkiel-Ivanovna** [comment]
Merci beaucoup pour l'aide apportée ! Mon école a retiré les Moyennes Générales et de la Classe sur l'interface. Du coup on est obligé de passer par l'API 😂.

Bonne Journée

**Comment by danhab05** [comment]
Hey J'ai une erreur 'Account type not supported' alors que mon compte marche en general trés bien jusqu'a hier

**Comment by Androz2091** [comment]
Bonjour @Snowy-27, est-ce que tu peux ouvrir une nouvelle issue pour ce problème ? Merci
(sachant que si tu utilises un compte Famille ça ne fonctionne plus, je ne savais pas si c'était vraiment utilisé - si c'est ton cas, ouvre une issue en demandant qu'on le rajoute de nouveau proprement)

**Comment by rieffelalice28-jpg** [comment]
comment je peux calculer ma moyenne
