### ISSUE TITLE
Compte famille

### ISSUE THREAD

**Issue by danhab05** [Androz2091/node-ecole-directe#4]
Bonjour serait t'il possible d'ajouter les comptes famille sur l'api.

**Comment by Derpinou** [comment]
Bonjour, il y avais bel et bien une fonctionnalité famille dans le package, je vous redirige donc vers le lien du commit qui l’as avec la documentation fournie avec.
https://github.com/Androz2091/node-ecole-directe/tree/e59e2e4ff94b23380bbe261ee7369d509211d90a

**Comment by danhab05** [comment]
> Bonjour, il y avais bel et bien une fonctionnalité famille dans le package, je vous redirige donc vers le lien du commit qui l’as avec la documentation fournie avec.
> https://github.com/Androz2091/node-ecole-directe/tree/e59e2e4ff94b23380bbe261ee7369d509211d90a

Merci je vais voir

**Comment by Androz2091** [comment]
Bonjour, la version famille pourra être rajoutée dans le futur (je n'ai pas d'identifiants Famille, donc je l'ai enlevée dans la dernière MAJ, j'imaginais qu'elle était cassée).

Le lien envoyé par @Derpinou est actuellement la meilleure solution mais il correspond à une ancienne version de la librairie, donc ce n'est pas l'idéal.

**Comment by Derpinou** [comment]
Re-bonsoir, suite a une série de tests, je peux confirmer que toutes les méthodes montrées dans la documentations marchent bel et bien niveau famille, malheureusement la documentation du commit que j'ai fournis n'est pas à jour car elle ne marche que pour 2019, si tu ne te sens capable  de modifier le code tout seul, je t'invite à rejoindre le serveur discord AndrozDev: https://discord.gg/KwBmqFqBPM
Le lien va te rediriger directement dans le salon d'aides de ce package, et je serais ravi de t'aider, je te souhaite une bonne soirée, et a bientôt sur AndrozDev :))
Cordialement,
Derp

**Comment by Androz2091** [comment]
C'est bon, les comptes Familles sont de nouveau supportés :tada:
Merci à @Derpinou pour ses identifiants et sa pr 👌

**Comment by Snowy-27** [comment]
> C'est bon, les comptes Familles sont de nouveau supportés :tada:
> Merci à @Derpinou pour ses identifiants et sa pr 👌 

Merci
