### ISSUE TITLE
-

### ISSUE THREAD

**Issue by euhjs** [Androz2091/node-ecole-directe#7]
-

**Comment by Flymeth** [comment]
même probleme

**Comment by Volnetiks** [comment]
Problème normalement résolu avec cette [pull request](https://github.com/Androz2091/node-ecole-directe/pull/9)
Vous pouvez directement reprendre l'exemple dans note_bac.js pour utiliser les modèles.

**Comment by ghost** [comment]
pour ma part ca n'est pas fix j ai toujours le Invalid credentials

**Comment by marceaupatu123** [comment]
Ce problème devrait être résolu avec ce pull request : #8

**Comment by Baraban511** [comment]
Après avoir installé ce pull request : [#8](https://github.com/Androz2091/node-ecole-directe/pull/8) je tombe sur : Error: Format JSON invalide. Comment peut-on résoudre le problème ?

**Comment by marceaupatu123** [comment]
> Après avoir installé ce pull request : [#8](https://github.com/Androz2091/node-ecole-directe/pull/8) je tombe sur : Error: Format JSON invalide. Comment peut-on résoudre le problème ?

Puis-je avoir la partie du code posant problème ?

**Comment by Baraban511** [comment]
> > Après avoir installé ce pull request : [#8](https://github.com/Androz2091/node-ecole-directe/pull/8) je tombe sur : Error: Format JSON invalide. Comment peut-on résoudre le problème ?
> 
> 
> 
> Puis-je avoir la partie du code posant problème ?

ˋˋˋ client.on('interactionCreate', async interaction => {
	if (interaction.type !== InteractionType.ModalSubmit) return;
	if (interaction.customId === 'ED_DATA') {
		await interaction.reply({ content: 'Nous traitons votre demande.' });
		// Get the data entered by the user

		const ED_ID = interaction.fields.getTextInputValue('ED_ID');
		const ED_MDP = interaction.fields.getTextInputValue('ED_MDP');

		const compte = await session.connexion(ED_ID, ED_MDP);
		// Vous êtes maintenant connecté à école directe !
		console.log(compte);
	}
});
ˋˋˋ
C'est un extrait de bot Discord. Ma théorie est qu'actuellement, c'est les vacances et que mon compte EcoleDirecte est donc 'inhabituelle'. Je pensais réessayer à la rentrée.

**Comment by Baraban511** [comment]
> > Après avoir installé ce pull request : [#8](https://github.com/Androz2091/node-ecole-directe/pull/8) je tombe sur : Error: Format JSON invalide. Comment peut-on résoudre le problème ?
> 
> Puis-je avoir la partie du code posant problème ?

C'est le code d'example.
